/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package MSASpeciesReplacer;

import java.io.*;
import javax.swing.*;

/**
 *
 * @author John Uhrig
 */
public class GUI extends javax.swing.JFrame {
    JFileChooser fc;
    File inputFile;
    File replacementTableFile;
    File outputFile;
    
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        fc = new JFileChooser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputFileTextBox = new javax.swing.JTextField();
        inputFileBrowseButton = new javax.swing.JButton();
        replacementTableTextBox = new javax.swing.JTextField();
        replaceTableBrowseButton = new javax.swing.JButton();
        outputFileTextBox = new javax.swing.JTextField();
        outputFileButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputFileTextBox.setEditable(false);
        inputFileTextBox.setText("Input file:");
        inputFileTextBox.setToolTipText("Input file - the file containing accession numbers to be replaced");
        inputFileTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFileTextBoxActionPerformed(evt);
            }
        });

        inputFileBrowseButton.setText("Browse...");
        inputFileBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFileBrowseButtonActionPerformed(evt);
            }
        });

        replacementTableTextBox.setEditable(false);
        replacementTableTextBox.setText("Replacement Table - CSV");
        replacementTableTextBox.setToolTipText("Input file - the file containing accession numbers to be replaced");
        replacementTableTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replacementTableTextBoxActionPerformed(evt);
            }
        });

        replaceTableBrowseButton.setText("Browse...");
        replaceTableBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceTableBrowseButtonActionPerformed(evt);
            }
        });

        outputFileTextBox.setEditable(false);
        outputFileTextBox.setText("Output filename");
        outputFileTextBox.setToolTipText("Input file - the file containing accession numbers to be replaced");
        outputFileTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputFileTextBoxActionPerformed(evt);
            }
        });

        outputFileButton.setText("Save As...");
        outputFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputFileButtonActionPerformed(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Multiple Sequence Alignment Accession Replacer");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 56, Short.MAX_VALUE)
                .add(jLabel1)
                .add(86, 86, 86))
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(25, 25, 25)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(outputFileTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 217, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(replacementTableTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 217, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(inputFileTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 217, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(37, 37, 37)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(inputFileBrowseButton)
                            .add(replaceTableBrowseButton)
                            .add(outputFileButton)))
                    .add(layout.createSequentialGroup()
                        .add(197, 197, 197)
                        .add(submitButton)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jLabel1)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(inputFileBrowseButton)
                    .add(inputFileTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(replacementTableTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(replaceTableBrowseButton))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(outputFileTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(outputFileButton))
                .add(27, 27, 27)
                .add(submitButton)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputFileTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFileTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFileTextBoxActionPerformed

    private void inputFileBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFileBrowseButtonActionPerformed

        int file = fc.showOpenDialog(this);
        if(file == JFileChooser.APPROVE_OPTION)
        {
            inputFileTextBox.setText(fc.getSelectedFile().toString());
            inputFile = fc.getSelectedFile();
            
        }
      
    }//GEN-LAST:event_inputFileBrowseButtonActionPerformed

    private void replacementTableTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replacementTableTextBoxActionPerformed
        
    }//GEN-LAST:event_replacementTableTextBoxActionPerformed

    private void replaceTableBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceTableBrowseButtonActionPerformed

        int file = fc.showOpenDialog(this);
        if(file == JFileChooser.APPROVE_OPTION)
        {
            replacementTableTextBox.setText(fc.getSelectedFile().toString());
            replacementTableFile = fc.getSelectedFile();
        }
    }//GEN-LAST:event_replaceTableBrowseButtonActionPerformed

    private void outputFileTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputFileTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputFileTextBoxActionPerformed

    private void outputFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputFileButtonActionPerformed

        int file = fc.showSaveDialog(this);
        if(file == JFileChooser.APPROVE_OPTION)
        {
           outputFileTextBox.setText(fc.getSelectedFile().toString());
           outputFile = fc.getSelectedFile();
        }
    }//GEN-LAST:event_outputFileButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if(inputFile != null && inputFile.exists())
        {
            if(replacementTableFile != null && replacementTableFile.exists())
            {
                if(outputFile != null)
                {
                 Replacer replace = new Replacer(inputFile, replacementTableFile, outputFile);
                 JOptionPane.showMessageDialog(this, "Done!");   
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Error, can't write to output file, please pick a new one."); 
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Error! Please select a valid replacement table"); 
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Error! Please select a valid input file."); 
        }
        
        
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inputFileBrowseButton;
    private javax.swing.JTextField inputFileTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton outputFileButton;
    private javax.swing.JTextField outputFileTextBox;
    private javax.swing.JButton replaceTableBrowseButton;
    private javax.swing.JTextField replacementTableTextBox;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
